CREATE TABLE house
(
ID int(11) PRIMARY KEY AUTO_INCREMENT,
Entrance float(11) NOT NULL,
Entrancey float(11) NOT NULL,
Entrancez float(11) NOT NULL,
Exitx float(11) NOT NULL,
Exity float(11) NOT NULL,
Exitz float(11) NOT NULL,
HealthUpgrade int(11) NOT NULL,
ArmourUpgrade int(11) NOT NULL,
Owner varchar(30)  NOT NULL,
Discription varchar(80)  NOT NULL,
Value int(11) NOT NULL,
Hel int(11) NOT NULL,
Arm int(11) NOT NULL,
`Int` int(11) NOT NULL,
`Lock` int(11) NOT NULL,
Owned int(11) NOT NULL,
Rooms int(11) NOT NULL,
Rent int(11) NOT NULL,
Rentabil int(11) NOT NULL,
Takings int(11) NOT NULL,
Vec int(11) NOT NULL,
Vcol1 int(11) NOT NULL,
Vcol2 int(11) NOT NULL,
`Date` int(11) NOT NULL,
Level int(11) NOT NULL,
World int(11) NOT NULL
)
